version: '3.9'
services:

  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
      #- ./db:/var/lib/postgresql/data
      #- database-kan:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB:kanban
      - POSTGRES_USER:kanban
      - POSTGRES_PASSWORD:kanban

  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    environment:
      - DB_SERVER=kanban-postgres
    ports:
      - 8080:8080
    links:
      - kanban-postgres

  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    ports:
      - 8081:80
    links:
      - kanban-app


volumes:
  kanban-data:
  #database-kan:
   # - type: bind
    #  source: ./database-data
     # target: /var/lib/postgresql/data